<?php
/**
 * Copyright © Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * See COPYING.txt for license details.
 */
?>
<?php
$class = $block->getType();
$image = 'most_viewed_products_list';
$items = $block->getItems();
$showAddTo = true;
$showCart  = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
?>
<?php if ($block->getItems()->getSize()) : ?>
<div class="block <?= $block->escapeHtml($class) ?>">
    <div class="block-title title">
        <strong id="block-<?= $block->escapeHtml($class) ?>-heading" role="heading" aria-level="2"><?= $block->escapeHtml($block->getTitle()) ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtml($class) ?>-heading">
        <div class="products wrapper grid products-grid products-<?= $block->escapeHtml($class) ?>">
            <ol class="products list items product-items">
                <?php $iterator = 1 ?>
                <?php foreach ($items as $item) : ?>
                    <?= ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info">
                        <?= '<!-- ' . $image . '-->' ?>
                        <a href="<?= $block->escapeHtml($block->getProductUrl($item)) ?>" class="product photo product-item-photo">
                            <?= $block->getImage($item, $image)->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($item->getName()) ?>" href="<?= $block->escapeHtml($block->getProductUrl($item)) ?>">
                                <?= $block->escapeHtml($item->getName()) ?></a>
                            </strong>
                            <?= $block->getProductPrice($item) ?>
                                <?php if ($templateType) : ?>
                                    <?= $block->getReviewsSummaryHtml($item, $templateType) ?>
                                <?php endif ?>

                                <?php if ($showAddTo || $showCart) : ?>
                                    <div class="product actions product-item-actions">
                                        <?php if ($showCart) : ?>
                                            <div class="actions-primary">
                                                <?php if ($item->isSaleable()) : ?>
                                                    <?php if ($item->getTypeInstance()->hasRequiredOptions($item)) : ?>
                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeHtml($block->getAddToCartUrl($item)) ?>"}}' type="button" title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php else : ?>
                                                        <?php $postDataHelper = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class);
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($item), ['product' => $item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?= $block->escapeHtml($postData) ?>'
                                                                type="button" title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php endif ?>
                                                <?php else : ?>
                                                    <?php if ($item->getIsSalable()) : ?>
                                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                    <?php else : ?>
                                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                    <?php endif ?>
                                                <?php endif ?>
                                            </div>
                                        <?php endif ?>

                                        <?php if ($showAddTo) : ?>
                                            <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                <?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
                                                    <?= $addToBlock->setProduct($item)->getChildHtml() ?>
                                                <?php endif ?>
                                            </div>
                                        <?php endif ?>
                                    </div>
                                <?php endif ?>
                            </div>
                        </div>
                    <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif ?>
